### PR TITLE
updated the style file for project section

### PR DESCRIPTION
**Pull request by Priyanshu-su30**
#91

### CODE REVIEW

**Comment by fykaa** [comment]
This code doesn't works, Watch the [deploy preview](https://deploy-preview-94--fykaa.netlify.app/)  @Priyanshu-su30

**Comment by Priyanshu-su30** [comment]
Have u merged the css file??

**Comment by fykaa** [comment]
@Priyanshu-su30 The deployed preview shows the changes a after merging

**Comment by Priyanshu-su30** [comment]
> This code doesn't works, Watch the [deploy preview](https://deploy-preview-94--fykaa.netlify.app/) @Priyanshu-su30

but this link shows the old file

**Pull request closed without merging**
